run-name: This workflow starts oidc token acquiring
on: workflow_call

permissions:
  id-token: write
  contents: read

jobs:
  reusable-workflow-call:
    runs-on: ubuntu-latest
    steps:
      - run: env

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)
