run-name: This workflow calls reusable workflow
on: push

jobs:
  call-reusable-workflow:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    steps:
      # - uses: ./.github/workflows/called-workflow.yaml
      - uses: actions/checkout@v4
      # - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ./.npmrc
      # - run: cat ./.npmrc
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm i
